export const KEY = {
  PRODUCTS: "products",
  PRODUCT: "product",
  USERS: "users",
  USER: "user",
  ROLES: "roles",
  PROGRAMS: "programs",
  ORDERS: "orders",
  SALES: "sales",
  PRODUCT_ATTRIBUTES: "product-attributes",
  PRODUCT_DEPARTMENTS: "product-departments",
  CART: "cart",
  ANNOUNCEMENTS: "announcements",
  DASHBOARD: {
    ORDERS: "dashboard-orders",
    ORDER: "dashboard-order",
    SALES: "dashboard-sales",
    ANNOUNCEMENT: "dashboard-announcements",
  },
  STUDENTS: {
    ALL: "all-students",
  },
  ME: "me",
  RETURN_ITEMS: "return-items",
  ACTIVITY_LOGS: "activity-logs",
}
